name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
      # everything in the following steps will be running on this conder instead of on the virtual machine
    steps:
      - name: Log node version
        run: |
          node -v 
          cat /etc/os-release
