name: Matrix
on: push
jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log mode node-version
        run: node -v
      # set a new version
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log mode node-version
        run: node -v
